# .air.toml

# Эта секция определяет, какие файлы отслеживаются и что происходит при изменении
[build]
  cmd = "go run cmd/main.go"  # Команда, которая будет запускаться для перезапуска
  bin = "tmp/main"  # Путь к бинарному файлу, который будет создаваться
  exclude_dir = ["assets", "tmp", "vendor"]  # Директории, которые не должны отслеживаться
  include_ext = ["go"]  # Файлы с этим расширением будут отслеживаться

[watch]
  root = "."  # Директория, от которой будет отслеживаться проект
  delay = 1000  # Задержка в миллисекундах перед перезапуском