services:
  farm_app_container:
    build: .
    container_name: farm_app
    ports:
      - "8080:8080"
    depends_on:
      - farm_db_container
    environment:
      APP_PORT: 8080
      DB_HOST: farm_db_container
      DB_PORT: 5432
      DB_USER: farm
      DB_PASSWORD: farm
      DB_NAME: farm

  farm_db_container:
    image: postgres:17
    container_name: farm_db
    restart: always
    environment:
      POSTGRES_USER: farm
      POSTGRES_PASSWORD: farm
      POSTGRES_DB: farm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
